
public class MyException1 extends System.Exception {
    let myField = throw "test" /* please work */;

    public def doSomething () {
        throw new MyException1();
    }

    public def somethingElse (one, two, three, four, five) {
        try {
            doSomething();
        }
        catch {
            (e: System.ArgumentException) => System.Console.WriteLine(e);
            f: System.InvalidOperationException => {
                System.Console.WriteLine("Something bád happened!");
            };
            _ => printfn("this is the default handler");
        }
        finally {
            // take out the trash
            one.Dispose();
        }
    }
}
